name: Build and Release JobSearchTool

on:
  push:
    tags:
      - "v*"   # Trigger on tags like v1.0.0
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (required if manual run)'
        required: false
        default: ''

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --windowed tik.py --name JobSearchTool

      - name: Determine Tag
        id: tag
        shell: pwsh
        run: |
          if ($env:GITHUB_REF -like 'refs/tags/*') {
              # Workflow triggered by tag push
              $tag = $env:GITHUB_REF -replace 'refs/tags/', ''
              Write-Output "tag_name=$tag" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8
          } else {
              # Manual run, use workflow input
              if ("${{ github.event.inputs.tag }}" -eq "") {
                  Write-Error "Error: You must provide a tag for manual run."
                  exit 1
              }
              Write-Output "tag_name=${{ github.event.inputs.tag }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8
          }

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/JobSearchTool.exe
          tag_name: ${{ steps.tag.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.ajira  }}
